# Generated by Django 5.2.11 on 2026-02-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responderteam',
            old_name='name',
            new_name='team_name',
        ),
    ]
