# Generated by Django 5.2.11 on 2026-02-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='incident_attachments/%Y/%m/%d/'),
        ),
    ]
