# Generated by Django 5.2.11 on 2026-02-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incidentstatushistory_incidentupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
